# Generated by Django 4.1 on 2022-10-15 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbRacacor',
            fields=[
                ('rcc_codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('rcc_racacor', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TbSexos',
            fields=[
                ('sex_codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('sex_sexo', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TbInformacoes',
            fields=[
                ('inf_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('inf_idapi', models.CharField(max_length=25, unique=True)),
                ('inf_idade', models.IntegerField(blank=True, null=True)),
                ('inf_datainiciosintomas', models.DateTimeField(blank=True, null=True)),
                ('inf_assintomatico', models.IntegerField(blank=True, null=True)),
                ('inf_dordecabeca', models.IntegerField(blank=True, null=True)),
                ('inf_febre', models.IntegerField(blank=True, null=True)),
                ('inf_disturbiosgustativos', models.IntegerField(blank=True, null=True)),
                ('inf_dordegarganta', models.IntegerField(blank=True, null=True)),
                ('inf_disturbiosolfativos', models.IntegerField(blank=True, null=True)),
                ('inf_dispneia', models.IntegerField(blank=True, null=True)),
                ('inf_tosse', models.IntegerField(blank=True, null=True)),
                ('inf_coriza', models.IntegerField(blank=True, null=True)),
                ('inf_outros', models.IntegerField(blank=True, null=True)),
                ('inf_rbv_codigo', models.IntegerField(blank=True, null=True)),
                ('inf_rcc_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informacao.tbracacor')),
                ('inf_sex_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informacao.tbsexos')),
            ],
        ),
    ]
