# Generated by Django 4.1 on 2022-10-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbinformacoes',
            name='inf_idapi',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
