# Generated by Django 4.1 on 2022-10-25 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informacao', '0002_alter_tbinformacoes_inf_idapi'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbinformacoes',
            name='inf_codigoResultadoTeste1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbinformacoes',
            name='inf_evolucaoCaso',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
