# Generated by Django 4.1 on 2022-10-30 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informacao', '0003_tbinformacoes_inf_codigoresultadoteste1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbinformacoes',
            name='inf_codigoResultadoTeste1',
        ),
    ]
