# Generated by Django 4.1 on 2022-10-25 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InformacaoTbinformacoes',
            fields=[
                ('inf_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('inf_idade', models.IntegerField(blank=True, null=True)),
                ('inf_datainiciosintomas', models.DateTimeField(blank=True, null=True)),
                ('inf_assintomatico', models.IntegerField(blank=True, null=True)),
                ('inf_dordecabeca', models.IntegerField(blank=True, null=True)),
                ('inf_febre', models.IntegerField(blank=True, null=True)),
                ('inf_disturbiosgustativos', models.IntegerField(blank=True, null=True)),
                ('inf_dordegarganta', models.IntegerField(blank=True, null=True)),
                ('inf_disturbiosolfativos', models.IntegerField(blank=True, null=True)),
                ('inf_dispneia', models.IntegerField(blank=True, null=True)),
                ('inf_tosse', models.IntegerField(blank=True, null=True)),
                ('inf_coriza', models.IntegerField(blank=True, null=True)),
                ('inf_outros', models.IntegerField(blank=True, null=True)),
                ('inf_rbv_codigo', models.IntegerField(blank=True, null=True)),
                ('inf_idapi', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'informacao_tbinformacoes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InformacaoTbracacor',
            fields=[
                ('rcc_codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('rcc_racacor', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'informacao_tbracacor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InformacaoTbsexos',
            fields=[
                ('sex_codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('sex_sexo', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'informacao_tbsexos',
                'managed': False,
            },
        ),
    ]
